name: flutter_ithome
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  
  dio: ^4.0.6
  flutter_html: ^2.2.1
  logger: ^1.1.0
  url_launcher: ^6.1.2
  flutter_easyrefresh: ^2.2.1
  extended_image: ^6.2.0
  oktoast: ^3.2.0
  remixicon: ^1.0.0
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  intl: 0.17.0
  carousel_slider: 4.1.1
  badges: ^2.0.3
  get: ^4.6.5
  share_plus: ^4.0.7
  dart_des: ^1.0.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  hive_generator: ^1.1.3
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/icon/
    - assets/logo/
    - assets/status/
  uses-material-design: true

